name: first github action
on : 
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  newjob:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      # checking out github repository
     
      - run: echo "hello world"
      # single line script

      - run: |
            echo "script1"
            echo "script2"
